/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.xplordat.kbe.avro;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class RawVertex extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 6203190760510830918L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"RawVertex\",\"namespace\":\"com.xplordat.kbe.avro\",\"fields\":[{\"name\":\"sensor\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"production_time\",\"type\":\"long\"},{\"name\":\"X\",\"type\":\"double\"},{\"name\":\"Y\",\"type\":\"double\"},{\"name\":\"production_order\",\"type\":\"long\"},{\"name\":\"arrival_order\",\"type\":\"long\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<RawVertex> ENCODER =
      new BinaryMessageEncoder<RawVertex>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<RawVertex> DECODER =
      new BinaryMessageDecoder<RawVertex>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<RawVertex> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<RawVertex> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<RawVertex> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<RawVertex>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this RawVertex to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a RawVertex from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a RawVertex instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static RawVertex fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private java.lang.String sensor;
   private long production_time;
   private double X;
   private double Y;
   private long production_order;
   private long arrival_order;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public RawVertex() {}

  /**
   * All-args constructor.
   * @param sensor The new value for sensor
   * @param production_time The new value for production_time
   * @param X The new value for X
   * @param Y The new value for Y
   * @param production_order The new value for production_order
   * @param arrival_order The new value for arrival_order
   */
  public RawVertex(java.lang.String sensor, java.lang.Long production_time, java.lang.Double X, java.lang.Double Y, java.lang.Long production_order, java.lang.Long arrival_order) {
    this.sensor = sensor;
    this.production_time = production_time;
    this.X = X;
    this.Y = Y;
    this.production_order = production_order;
    this.arrival_order = arrival_order;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return sensor;
    case 1: return production_time;
    case 2: return X;
    case 3: return Y;
    case 4: return production_order;
    case 5: return arrival_order;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: sensor = value$ != null ? value$.toString() : null; break;
    case 1: production_time = (java.lang.Long)value$; break;
    case 2: X = (java.lang.Double)value$; break;
    case 3: Y = (java.lang.Double)value$; break;
    case 4: production_order = (java.lang.Long)value$; break;
    case 5: arrival_order = (java.lang.Long)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'sensor' field.
   * @return The value of the 'sensor' field.
   */
  public java.lang.String getSensor() {
    return sensor;
  }


  /**
   * Sets the value of the 'sensor' field.
   * @param value the value to set.
   */
  public void setSensor(java.lang.String value) {
    this.sensor = value;
  }

  /**
   * Gets the value of the 'production_time' field.
   * @return The value of the 'production_time' field.
   */
  public long getProductionTime() {
    return production_time;
  }


  /**
   * Sets the value of the 'production_time' field.
   * @param value the value to set.
   */
  public void setProductionTime(long value) {
    this.production_time = value;
  }

  /**
   * Gets the value of the 'X' field.
   * @return The value of the 'X' field.
   */
  public double getX() {
    return X;
  }


  /**
   * Sets the value of the 'X' field.
   * @param value the value to set.
   */
  public void setX(double value) {
    this.X = value;
  }

  /**
   * Gets the value of the 'Y' field.
   * @return The value of the 'Y' field.
   */
  public double getY() {
    return Y;
  }


  /**
   * Sets the value of the 'Y' field.
   * @param value the value to set.
   */
  public void setY(double value) {
    this.Y = value;
  }

  /**
   * Gets the value of the 'production_order' field.
   * @return The value of the 'production_order' field.
   */
  public long getProductionOrder() {
    return production_order;
  }


  /**
   * Sets the value of the 'production_order' field.
   * @param value the value to set.
   */
  public void setProductionOrder(long value) {
    this.production_order = value;
  }

  /**
   * Gets the value of the 'arrival_order' field.
   * @return The value of the 'arrival_order' field.
   */
  public long getArrivalOrder() {
    return arrival_order;
  }


  /**
   * Sets the value of the 'arrival_order' field.
   * @param value the value to set.
   */
  public void setArrivalOrder(long value) {
    this.arrival_order = value;
  }

  /**
   * Creates a new RawVertex RecordBuilder.
   * @return A new RawVertex RecordBuilder
   */
  public static com.xplordat.kbe.avro.RawVertex.Builder newBuilder() {
    return new com.xplordat.kbe.avro.RawVertex.Builder();
  }

  /**
   * Creates a new RawVertex RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new RawVertex RecordBuilder
   */
  public static com.xplordat.kbe.avro.RawVertex.Builder newBuilder(com.xplordat.kbe.avro.RawVertex.Builder other) {
    if (other == null) {
      return new com.xplordat.kbe.avro.RawVertex.Builder();
    } else {
      return new com.xplordat.kbe.avro.RawVertex.Builder(other);
    }
  }

  /**
   * Creates a new RawVertex RecordBuilder by copying an existing RawVertex instance.
   * @param other The existing instance to copy.
   * @return A new RawVertex RecordBuilder
   */
  public static com.xplordat.kbe.avro.RawVertex.Builder newBuilder(com.xplordat.kbe.avro.RawVertex other) {
    if (other == null) {
      return new com.xplordat.kbe.avro.RawVertex.Builder();
    } else {
      return new com.xplordat.kbe.avro.RawVertex.Builder(other);
    }
  }

  /**
   * RecordBuilder for RawVertex instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<RawVertex>
    implements org.apache.avro.data.RecordBuilder<RawVertex> {

    private java.lang.String sensor;
    private long production_time;
    private double X;
    private double Y;
    private long production_order;
    private long arrival_order;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.xplordat.kbe.avro.RawVertex.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.sensor)) {
        this.sensor = data().deepCopy(fields()[0].schema(), other.sensor);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.production_time)) {
        this.production_time = data().deepCopy(fields()[1].schema(), other.production_time);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.X)) {
        this.X = data().deepCopy(fields()[2].schema(), other.X);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.Y)) {
        this.Y = data().deepCopy(fields()[3].schema(), other.Y);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.production_order)) {
        this.production_order = data().deepCopy(fields()[4].schema(), other.production_order);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.arrival_order)) {
        this.arrival_order = data().deepCopy(fields()[5].schema(), other.arrival_order);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
    }

    /**
     * Creates a Builder by copying an existing RawVertex instance
     * @param other The existing instance to copy.
     */
    private Builder(com.xplordat.kbe.avro.RawVertex other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.sensor)) {
        this.sensor = data().deepCopy(fields()[0].schema(), other.sensor);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.production_time)) {
        this.production_time = data().deepCopy(fields()[1].schema(), other.production_time);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.X)) {
        this.X = data().deepCopy(fields()[2].schema(), other.X);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.Y)) {
        this.Y = data().deepCopy(fields()[3].schema(), other.Y);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.production_order)) {
        this.production_order = data().deepCopy(fields()[4].schema(), other.production_order);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.arrival_order)) {
        this.arrival_order = data().deepCopy(fields()[5].schema(), other.arrival_order);
        fieldSetFlags()[5] = true;
      }
    }

    /**
      * Gets the value of the 'sensor' field.
      * @return The value.
      */
    public java.lang.String getSensor() {
      return sensor;
    }


    /**
      * Sets the value of the 'sensor' field.
      * @param value The value of 'sensor'.
      * @return This builder.
      */
    public com.xplordat.kbe.avro.RawVertex.Builder setSensor(java.lang.String value) {
      validate(fields()[0], value);
      this.sensor = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'sensor' field has been set.
      * @return True if the 'sensor' field has been set, false otherwise.
      */
    public boolean hasSensor() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'sensor' field.
      * @return This builder.
      */
    public com.xplordat.kbe.avro.RawVertex.Builder clearSensor() {
      sensor = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'production_time' field.
      * @return The value.
      */
    public long getProductionTime() {
      return production_time;
    }


    /**
      * Sets the value of the 'production_time' field.
      * @param value The value of 'production_time'.
      * @return This builder.
      */
    public com.xplordat.kbe.avro.RawVertex.Builder setProductionTime(long value) {
      validate(fields()[1], value);
      this.production_time = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'production_time' field has been set.
      * @return True if the 'production_time' field has been set, false otherwise.
      */
    public boolean hasProductionTime() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'production_time' field.
      * @return This builder.
      */
    public com.xplordat.kbe.avro.RawVertex.Builder clearProductionTime() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'X' field.
      * @return The value.
      */
    public double getX() {
      return X;
    }


    /**
      * Sets the value of the 'X' field.
      * @param value The value of 'X'.
      * @return This builder.
      */
    public com.xplordat.kbe.avro.RawVertex.Builder setX(double value) {
      validate(fields()[2], value);
      this.X = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'X' field has been set.
      * @return True if the 'X' field has been set, false otherwise.
      */
    public boolean hasX() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'X' field.
      * @return This builder.
      */
    public com.xplordat.kbe.avro.RawVertex.Builder clearX() {
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'Y' field.
      * @return The value.
      */
    public double getY() {
      return Y;
    }


    /**
      * Sets the value of the 'Y' field.
      * @param value The value of 'Y'.
      * @return This builder.
      */
    public com.xplordat.kbe.avro.RawVertex.Builder setY(double value) {
      validate(fields()[3], value);
      this.Y = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'Y' field has been set.
      * @return True if the 'Y' field has been set, false otherwise.
      */
    public boolean hasY() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'Y' field.
      * @return This builder.
      */
    public com.xplordat.kbe.avro.RawVertex.Builder clearY() {
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'production_order' field.
      * @return The value.
      */
    public long getProductionOrder() {
      return production_order;
    }


    /**
      * Sets the value of the 'production_order' field.
      * @param value The value of 'production_order'.
      * @return This builder.
      */
    public com.xplordat.kbe.avro.RawVertex.Builder setProductionOrder(long value) {
      validate(fields()[4], value);
      this.production_order = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'production_order' field has been set.
      * @return True if the 'production_order' field has been set, false otherwise.
      */
    public boolean hasProductionOrder() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'production_order' field.
      * @return This builder.
      */
    public com.xplordat.kbe.avro.RawVertex.Builder clearProductionOrder() {
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'arrival_order' field.
      * @return The value.
      */
    public long getArrivalOrder() {
      return arrival_order;
    }


    /**
      * Sets the value of the 'arrival_order' field.
      * @param value The value of 'arrival_order'.
      * @return This builder.
      */
    public com.xplordat.kbe.avro.RawVertex.Builder setArrivalOrder(long value) {
      validate(fields()[5], value);
      this.arrival_order = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'arrival_order' field has been set.
      * @return True if the 'arrival_order' field has been set, false otherwise.
      */
    public boolean hasArrivalOrder() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'arrival_order' field.
      * @return This builder.
      */
    public com.xplordat.kbe.avro.RawVertex.Builder clearArrivalOrder() {
      fieldSetFlags()[5] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public RawVertex build() {
      try {
        RawVertex record = new RawVertex();
        record.sensor = fieldSetFlags()[0] ? this.sensor : (java.lang.String) defaultValue(fields()[0]);
        record.production_time = fieldSetFlags()[1] ? this.production_time : (java.lang.Long) defaultValue(fields()[1]);
        record.X = fieldSetFlags()[2] ? this.X : (java.lang.Double) defaultValue(fields()[2]);
        record.Y = fieldSetFlags()[3] ? this.Y : (java.lang.Double) defaultValue(fields()[3]);
        record.production_order = fieldSetFlags()[4] ? this.production_order : (java.lang.Long) defaultValue(fields()[4]);
        record.arrival_order = fieldSetFlags()[5] ? this.arrival_order : (java.lang.Long) defaultValue(fields()[5]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<RawVertex>
    WRITER$ = (org.apache.avro.io.DatumWriter<RawVertex>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<RawVertex>
    READER$ = (org.apache.avro.io.DatumReader<RawVertex>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.sensor);

    out.writeLong(this.production_time);

    out.writeDouble(this.X);

    out.writeDouble(this.Y);

    out.writeLong(this.production_order);

    out.writeLong(this.arrival_order);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.sensor = in.readString();

      this.production_time = in.readLong();

      this.X = in.readDouble();

      this.Y = in.readDouble();

      this.production_order = in.readLong();

      this.arrival_order = in.readLong();

    } else {
      for (int i = 0; i < 6; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.sensor = in.readString();
          break;

        case 1:
          this.production_time = in.readLong();
          break;

        case 2:
          this.X = in.readDouble();
          break;

        case 3:
          this.Y = in.readDouble();
          break;

        case 4:
          this.production_order = in.readLong();
          break;

        case 5:
          this.arrival_order = in.readLong();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










